-- ---------------------------------------------------------------------------
-- AI-review audit trail: any clinical impression generated by an AI model
-- must be logged verbatim before a human reviews and signs off on the note
-- it informed. Deliberately online-only — this table is never added to
-- SYNC_TABLES / the Dexie schema, so it does not appear in the offline
-- activity feed and cannot be created while offline.
-- ---------------------------------------------------------------------------
create table public.ai_generation_log (
  id uuid primary key default gen_random_uuid(),
  clinic_id uuid not null references public.clinics (id) on delete cascade,
  consultation_id uuid not null references public.consultation_notes (id) on delete cascade,
  raw_ai_output text not null,
  model_name text not null,
  created_at timestamptz not null default now()
);

create index ai_generation_log_consultation_idx
  on public.ai_generation_log (consultation_id);
create index ai_generation_log_clinic_idx
  on public.ai_generation_log (clinic_id, created_at);

alter table public.ai_generation_log enable row level security;

-- Tenant policy: visible to members of the clinic that owns the linked
-- consultation note, not just any clinic member globally.
create policy ai_generation_log_all on public.ai_generation_log
  for all using (is_clinic_member(clinic_id)) with check (is_clinic_member(clinic_id));

revoke insert, update, delete on public.ai_generation_log from anon;
